### ISSUE TITLE
Documentation for installation?

### ISSUE THREAD

**Issue by grantkemp** [magepal/magento1-google-tag-manager#13]
This is an excellent module however its not clear for developers what needs to happen to completd the installation after the module has been imported.  The details about the XML is really key to it working.  Ideall we should have a screen of what it looks like if its correctly installed.  

If someone can add install instructions to the read me it would be great.  I don't mind adding a bit on how to test the dataLayer objects from GTM perspective. 

Great job on this module!

**Comment by srenon** [comment]
@grantkemp .... can you compile a list of all your questions and I will try to answer them as best as possible?

**Comment by grantkemp** [comment]
Thanks @srenon  - just one question - is there any instructions for how the developer should install the module. 
It mentions something in the read me about adding XML - but doesn't specify what XML should be added and to where.  

If this is indicated elsewhere- can you link to that location from the readme/ elsewhere?

**Comment by srenon** [comment]
@grantkemp ... Sorry for the confusion, the only thing you need to do is install the extension and enter your account id in admin.

Advanced users could use layout XML to add additional value to the data layer

Example, if you want the cart to be a high-value page
```

<?xml version="1.0"?>
<layout version="1.0.0">
    <checkout_cart_index>
         <reference name="magepal_gtm_datalayer">
              <action method="addVariable">
                 <name>visitorType</name>
                 <value>high-value</value>
              </action>
        </reference>
    </checkout_cart_index>
</layout>

```

**Comment by paalsoberg** [comment]
Hey great module, just one question the datalayer push through the catalog_category_view, catalog_product_view etc rather than product, category, cart etc which is what the google adwords / dynamic remarketing expects. Any ideas?

**Comment by grantkemp** [comment]
Thanks @srenon  - I am not seeing the tag manager snippet or the data layer on the site we are testing it on.  It might be that the layout has been customized too much.  Do you have any ideas of where to look if its not showing up?

**Comment by srenon** [comment]
@grantkemp .. Did you add your account id and enable the module?

**Comment by alex-koepke** [comment]
@grantkemp what do you get when you type `dataLayer` into the console of your browser? 
You should see something like the following. 
![screen shot 2017-08-15 at 9 43 54 am](https://user-images.githubusercontent.com/10850217/29318606-d61a4034-819e-11e7-98e5-0da83dcd9d2d.png)

**Comment by grantkemp** [comment]
Hi @alex-koepke  and @srenon  - thanks for the follow up.  We had another legacy version of GTM in the code which was overriding it - when we removed it , the snippet code appeared nicely. 

I have one more issue though which is the snippets aren't appearing on each of the pages that they should be.  
I can't really see the datalayer calls for productImpressions or Checkout - would these need to be hand customized?

It would be excellent to have a list of the sample data layer calls. Then we can add others on our projects and share the code back. (if approved)

The starting ones that I would use are:
- Cat Page - [Product Impressions(https://developers.google.com/tag-manager/enhanced-ecommerce#product-impressions) - 
- PDP Page - ProductDetail
- Checkout - Checkout Call 
- Order Confirmation - Purchase call

**Comment by grantkemp** [comment]
After digging into the code - this feels more like a feature request now - so I have added it as a seperate issue #14. Feel free to close this - thanks for the support
