### ISSUE TITLE
How to install the plugin?

### ISSUE THREAD

**Issue by BennyAlex** [magepal/magento1-google-tag-manager#34]
Hello,
the SEO agency for our client want me to install this plugin.
Unfortunatelly there is no install guide in your readme. Can you provide some details on this topic, please?
Thanks in advance.

**Comment by quisse** [comment]
https://www.magepal.com/help/how-to/google-tag-manager/magento-gtm-ga4-json-import/

**Comment by srenon** [comment]
@quisse to use our GA4 container you will also need our Ga4 extension @ https://www.magepal.com/magento1/google-tag-manager-1.html

**Comment by quisse** [comment]
Oh so that one is different?

I'm installing that extension right now but the documentation wasn't working, thats how I landed here. I'm in contact with you via the magepal support I suppose.
